### ISSUE TITLE
Generating loot does not set proper amount in lootable NPC sheet

### ISSUE THREAD

**Issue by Boefjim** [rinnocenti/innocenti-loot#6]
When generating loot for multiple NPCs after a fight, it is common for some items to be added multiple times.
However, after generating such a loot sheet, it for some reason only has 1 of each item, as seen here:

![image](https://user-images.githubusercontent.com/16748131/148684808-81d207e7-705c-44bb-aa16-b0ee7790f10e.png)
_The generated loot message (properly displays amount)_

![image](https://user-images.githubusercontent.com/16748131/148684843-5db3be49-0a24-4069-aacb-012aef3800d8.png)
_The generated lootable NPC sheet (only has 1 of each item)_

**Comment by rinnocenti** [comment]
what is the system?
I'm seeing some changes in the loot sheet maybe that's it, because I can't reproduce it.

**Comment by Boefjim** [comment]
The system is dnd5e version 1.5.5 on Foundry version 0.8.9
Using the modules:
- DFReds Pocket Change 3.2.1
- Innocenti's Loot 0.2.4
- Loot Sheet NPC 5e 3.2.5

**Comment by rinnocenti** [comment]
I Update de Module for use in Foundry v9.5 and v10 now.

V8.9 is no longer supported
